export const actions = {
  SET_STUDENT_DETAILS: "SET_STUDENT_DETAILS",
  SET_STUDENT_BOOKSBORROWED: "SET_STUDENT_BOOKSBORROWED",
  SET_BOOKLIST: "SET_BOOKLIST",
  SET_ISSUEBOOKS: "SET_ISSUEBOOKS",
  INC_ISSUEBOOKS: "INC_ISSUEBOOKS",
  DEC_ISSUEBOOKS: "DEC_ISSUEBOOKS",
};
