export const actions = {
  SET_STUDENT_DETAILS: "SET_STUDENT_DETAILS",
  SET_STUDENT_BOOKSBORROWED: "SET_STUDENT_BOOKSBORROWED",
  SET_BOOKLIST: "SET_BOOKLIST",
  INC_ISSUEBOOKS: "INC_ISSUEBOOKS",
  DEC_ISSUEBOOKS: "DEC_ISSUEBOOKS",
  INC_RETURNBOOKS: "INC_RETURNBOOKS",
  DEC_RETURNBOOKS: "DEC_RETURNBOOKS",
  EMPTY_RETURNBOOKS: "EMPTY_RETURNBOOKS",
  EMPTY_ISSUEBOOKS: "EMPTY_ISSUEBOOKS",
  SET_PENDINGRETURNS: "SET_PENDINGRETURNS",
};
export const url = "http://3.111.218.168:4001";
// export const url = "http://localhost:4000";
